name: Devcontainer

on:
  push:
    paths:
      - .devcontainer/Dockerfile
  pull_request:
    paths:
      - .devcontainer/Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Build devcontainer image
        run: |
          docker build --file .devcontainer/Dockerfile .
